name: green_go
description: "App that encourages the use of sustainable means of transport"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_storage: ^11.0.1
  cloud_firestore: ^4.15.9
  geolocator: ^11.0.0
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.9.0
  firebase_storage: ^11.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/